alter table if exists accounts drop constraint if exists person_account;
alter table if exists payments drop constraint if exists payment_destination_account;
alter table if exists payments drop constraint if exists payment_source_account;
alter table if exists types drop constraint if exists account_type;

drop table if exists persons cascade;
drop table if exists accounts cascade;
drop table if exists payments cascade;
drop table if exists types cascade;

create table accounts (id int8 generated by default as identity, account_number varchar(255), balance numeric(19, 2), type_id int8, person_id int8, primary key (id));
create table payments (id int8 generated by default as identity, amount numeric(19, 2), reason varchar(255), status varchar(255), timestamp timestamp, destination_id int8, source_id int8, primary key (id));
create table persons (id int8 generated by default as identity, first_name varchar(255), last_name varchar(255), primary key (id));
create table types (id int8 generated by default as identity, name varchar(255), primary key (id));

alter table if exists accounts add constraint account_type foreign key (type_id) references types;
alter table if exists accounts add constraint person_account foreign key (person_id) references persons;
alter table if exists payments add constraint payment_destination_account foreign key (destination_id) references accounts;
alter table if exists payments add constraint payment_source_account foreign key (source_id) references accounts;