alter table if exists users drop constraint if exists user_person;
alter table if exists user_role drop constraint if exists roles;
alter table if exists user_role drop constraint if exists users;

drop table if exists users cascade;
drop table if exists roles cascade;
drop table if exists user_role cascade;

create table users (user_id int8 generated by default as identity, created timestamp, updated timestamp, email varchar(255), username varchar(255), password varchar(255), person_id int8, status varchar(255), primary key (user_id));
create table roles (role_id int8 generated by default as identity, role_name varchar(255), primary key (role_id));
create table user_role (user_id int8, role_id int8, primary key (user_id, role_id));

alter table if exists users add constraint user_person foreign key (person_id) references persons;
alter table if exists user_role add constraint roles foreign key (role_id) references roles;
alter table if exists user_role add constraint users foreign key (user_id) references users;